name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  setuptools:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: setuptools
  pybind11:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: pybind11
  poetry:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: poetry
  flit:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: flit
  flit621:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: flit621
  pdm:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: pdm
  trampolim:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: trampolim
      python-min: "3.7"
  whey:
    uses: scikit-hep/cookie/.github/workflows/each.yml@main
    with:
      backend: whey
  


  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build sdist and wheel
      run: pipx run nox --forcecolor -s dist

    - name: Show results
      run: ls -l dist

    - uses: actions/upload-artifact@v2
      with:
        path: dist
